remote-theme: StartBootstrap/startbootstrap-clean-blog-jekyll

title:              Gabriel's Blog
email:              gabriel.frechette@gmail.com
description:        Just a dude rambling on
author:             Gabriel Frechette
baseurl:            "/"
url:                "https://gabrinator.github.io"

# Social Profiles
twitter_username:   
github_username:    gabrinator
facebook_username:  
instagram_username: gabsquared 
linkedin_username:  gabrielfrechette

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
